### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Crainda** [jonassvensson4/jsfour-dna#1]
Hi, Thanks for making this script.  I'm trying to get it to work on my server, but I have some issues where when I go to get DNA from someone, nothing happens. No notifications or anything. I have the register script you made running aswell.

No Errors pop up in my f8 console or in the server console when I try to use the script. any help would be greatly appreciated.

**Comment by jnsvns** [comment]
And you've added it correctly in your menu?

**Comment by Crainda** [comment]
As Far as I can tell, I copied the example in the readme and posted it into my Cop job

    function(data, menu)

      if data.current.value == 'citizen_interaction' then

        ESX.UI.Menu.Open(
          'default', GetCurrentResourceName(), 'citizen_interaction',
          {
            title    = _U('citizen_interaction'),
            align    = 'top-left',
            elements = {
              {label = _U('id_card'),       value = 'identity_card'},
              {label = _U('search'),        value = 'body_search'},
              {label = _U('handcuff'),    value = 'handcuff'},
              {label = _U('drag'),      value = 'drag'},
              {label = _U('put_in_vehicle'),  value = 'put_in_vehicle'},
              {label = _U('out_the_vehicle'), value = 'out_the_vehicle'},
              {label = _U('fine'),            value = 'fine'},
	      {label = _U('jail'),            value = 'jail'},
	     {label = _U('dna'),             value = 'dna'},
            },
          },
          function(data2, menu2)

            local player, distance = ESX.Game.GetClosestPlayer()

            if distance ~= -1 and distance <= 3.0 then

              if data2.current.value == 'identity_card' then
                OpenIdentityCardMenu(player)
              end

              if data2.current.value == 'body_search' then
                OpenBodySearchMenu(player)
              end
			  

              if data2.current.value == 'handcuff' then
                TriggerServerEvent('esx_policejob:handcuff', GetPlayerServerId(player))
              end

              if data2.current.value == 'drag' then
                TriggerServerEvent('esx_policejob:drag', GetPlayerServerId(player))
              end

              if data2.current.value == 'put_in_vehicle' then
                TriggerServerEvent('esx_policejob:putInVehicle', GetPlayerServerId(player))
              end

              if data2.current.value == 'fine' then
                OpenFineMenu(player)
			
			  end
			  
			  if data2.current.value == 'jail' then
				JailPlayer(GetPlayerServerId(player))
				
			  end
			   if data.current.value == 'dna' then
			local player, distance = ESX.Game.GetClosestPlayer()
  
			if distance ~= -1 and distance <= 3.0 then
			TriggerEvent('jsfour-dna:get', player)
			end
			end

          end,
          function(data2, menu2)
            menu2.close()
          end
        )

      end

**Comment by jnsvns** [comment]
Yeah there's the problem. It's a EXAMPLE which means you may have to change some stuff.

`function(data, menu)

  if data.current.value == 'citizen_interaction' then

    ESX.UI.Menu.Open(
      'default', GetCurrentResourceName(), 'citizen_interaction',
      {
        title    = _U('citizen_interaction'),
        align    = 'top-left',
        elements = {
          {label = _U('id_card'),       value = 'identity_card'},
          {label = _U('search'),        value = 'body_search'},
          {label = _U('handcuff'),    value = 'handcuff'},
          {label = _U('drag'),      value = 'drag'},
          {label = _U('put_in_vehicle'),  value = 'put_in_vehicle'},
          {label = _U('out_the_vehicle'), value = 'out_the_vehicle'},
          {label = _U('fine'),            value = 'fine'},
      {label = _U('jail'),            value = 'jail'},
     {label = _U('dna'),             value = 'dna'},
        },
      },
      function(data2, menu2)

        local player, distance = ESX.Game.GetClosestPlayer()

        if distance ~= -1 and distance <= 3.0 then

          if data2.current.value == 'identity_card' then
            OpenIdentityCardMenu(player)
          end

          if data2.current.value == 'body_search' then
            OpenBodySearchMenu(player)
          end
		  

          if data2.current.value == 'handcuff' then
            TriggerServerEvent('esx_policejob:handcuff', GetPlayerServerId(player))
          end

          if data2.current.value == 'drag' then
            TriggerServerEvent('esx_policejob:drag', GetPlayerServerId(player))
          end

          if data2.current.value == 'put_in_vehicle' then
            TriggerServerEvent('esx_policejob:putInVehicle', GetPlayerServerId(player))
          end

          if data2.current.value == 'fine' then
            OpenFineMenu(player)
		
		  end
		  
		  if data2.current.value == 'jail' then
			JailPlayer(GetPlayerServerId(player))
		  end

                 if data2.current.value == 'dna' then
			TriggerEvent('jsfour-dna:get', player)
		 end


      end,
      function(data2, menu2)
        menu2.close()
      end
    )

  end`

**Comment by Crainda** [comment]
Ah, Well. I'm not very good when it comes to this coding stuff. I guess i'll try to figure it out with trial and error.

**Comment by jnsvns** [comment]
I just sent you a version that should work

**Comment by Crainda** [comment]
Oh wow, I'm blind. My bad. Testing it now. Thanks

**Comment by Crainda** [comment]
I put your version it, but now my F6 Menu for the job menu no longer opens for some reason.

**Comment by jnsvns** [comment]
Might have missed an end some where. Anyways.. You need to use this code if you want it to work and not the whole example I provided. Happy testing.

if data2.current.value == 'dna' then
    riggerEvent('jsfour-dna:get', player)
end
