### ISSUE TITLE
fetching DNA

### ISSUE THREAD

**Issue by oogienl** [jonassvensson4/jsfour-dna#3]
Hello, i have added the ''jsfour-dna:get'' into my police main.lua like this: https://pastebin.com/SKHLhE5M
when i press it ingame it works (kinda?) but it keeps grabbing my own DNA wich i can register in the system, but even that does not seem to function 100%. I cant figure out how to search for my own DNA when i use my 4 digits from jsfour-register. We tried with some other people killing eachother with melee weapons, everytime i get close to the body it keeps taking my own DNA. any suggestions what might be wrong? thanks in advance - oogie

**Comment by jnsvns** [comment]
I can't find where you've defined the variable "player" in your case it's named "closestPlayer"?

**Comment by jnsvns** [comment]
And I don't know what you mean by "I cant figure out how to search for my own DNA" there's no search function in my script

**Comment by oogienl** [comment]
worked, thank you very much
