### ISSUE TITLE
Issue with Uploading DNA

### ISSUE THREAD

**Issue by Kry0n** [jonassvensson4/jsfour-dna#4]
Hello! 
First want to say THANK YOU!!! Amazing resources you have made and all are working for me except this one small issue.

--Get DNA sample from player on ground. 
--Open the DNA-database at local PD and choose "Upload" (sits here without result)
Getting:
citizen:/scripting/lua/scheduler.lua:405: @jsfour-dna/server.lua:132: attempt to concatenate a nil 

Tired to show everything in one shot - http://prntscr.com/nmmobr
Any chance someone can point me in the right direction?

**Comment by Kry0n** [comment]
With more testing:
--I am able to grab DNA from player standing up.
--Open DNA-database at local pd
--Click "Upload" and I get "The person is already in our system"

**Comment by jnsvns** [comment]
That error means it can't find the lastdigits in the database. I'm assuming you've read the readme and followed the instructions. Check your users table for null values in that column

**Comment by Kry0n** [comment]
Thank you! I cleared all users in DB and its working. There were users with null values. 
I am now able to upload the DNA from dead body and I get a DNA with ID "3335495".


When I open Match DNA i enter the ID but get a No Match result. 
I checked the table jsfour_dna and see the ID

**Comment by jnsvns** [comment]
Did you upload the killers DNA to the database?

**Comment by Kry0n** [comment]
Ahh I get it. You track the killers DNA.  Wow...
Thank you so much - case closed
