### ISSUE TITLE
Grab my DNA...

### ISSUE THREAD

**Issue by Antykors** [jonassvensson4/jsfour-dna#5]
Hi, and sorry for my english...

When i grab DNA in menu F6 of policejob, and i go upload this, it's my DNA.

Please help me, my code is exactly like in the readme.

Thx

**Comment by jnsvns** [comment]
You can't grab your own DNA if it's been installed correctly in your menu

**Comment by Antykors** [comment]
My code is this : 

if data.current.value == 'citizen_interaction' then
			local elements = {
				{label = _U('id_card'),			value = 'identity_card'},
				{label = _U('search'),			value = 'body_search'},
				{label = _U('handcuff'),		value = 'handcuff'},
				{label = _U('drag'),			value = 'drag'},
				{label = _U('put_in_vehicle'),	value = 'put_in_vehicle'},
				{label = _U('out_the_vehicle'),	value = 'out_the_vehicle'},
				{label = _U('fine'),			value = 'fine'},
				{label = _U('unpaid_bills'),	value = 'unpaid_bills'},
				{label = "Récupérer de l\'ADN",             	value = 'dna'}
			}
			
			if data.current.value == 'dna' then
				local player, distance = ESX.Game.GetClosestPlayer()
  
  				if distance ~= -1 and distance <= 3.0 then
    				TriggerEvent('jsfour-dna:get', player)
  				end
  			end

**Comment by Antykors** [comment]
I modified to : 

```
function OpenPoliceActionsMenu()
	ESX.UI.Menu.CloseAll()

	ESX.UI.Menu.Open(
	'default', GetCurrentResourceName(), 'police_actions',
	{
	        title      = 'Police',
		align    = 'bottom-right',
		elements = {
			{label = _U('citizen_interaction'),	value = 'citizen_interaction'},
			{label = _U('vehicle_interaction'),	value = 'vehicle_interaction'},
			{label = _U('object_spawner'),		value = 'object_spawner'},
			{label = "Envoyer en prison",           value = 'jail_menu'},
			{label = "Récupérer de l\'ADN",             	value = 'dna'}
		}
	}, function(data, menu)

		if data.current.value == 'jail_menu' then
                     TriggerEvent("esx-qalle-jail:openJailMenu")
                end

                if data.current.value == 'dna' then
				local player, distance = ESX.Game.GetClosestPlayer()
  
  				if distance ~= -1 and distance <= 3.0 then
    				TriggerEvent('jsfour-dna:get', player)
  				end
  		end

		if data.current.value == 'citizen_interaction' then
			local elements = {
				{label = _U('id_card'),			value = 'identity_card'},
				{label = _U('search'),			value = 'body_search'},
				{label = _U('handcuff'),		value = 'handcuff'},
				{label = _U('drag'),			value = 'drag'},
				{label = _U('put_in_vehicle'),	value = 'put_in_vehicle'},
				{label = _U('out_the_vehicle'),	value = 'out_the_vehicle'},
				{label = _U('fine'),			value = 'fine'},
				{label = _U('unpaid_bills'),	value = 'unpaid_bills'}
			}

			if Config.EnableLicenses then
				table.insert(elements, { label = _U('license_check'), value = 'license' })
			end
		
			ESX.UI.Menu.Open(
			'default', GetCurrentResourceName(), 'citizen_interaction',
			{
				title    = _U('citizen_interaction'),
				align    = 'bottom-right',
				elements = elements
			}, function(data2, menu2)
				local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
				if closestPlayer ~= -1 and closestDistance <= 3.0 then
					local action = data2.current.value

					if action == 'identity_card' then
						OpenIdentityCardMenu(closestPlayer)
					elseif action == 'body_search' then
						TriggerServerEvent('esx_policejob:message', GetPlayerServerId(closestPlayer), _U('being_searched'))
						OpenBodySearchMenu(closestPlayer)
					elseif action == 'handcuff' then
						TriggerServerEvent('esx_policejob:handcuff', GetPlayerServerId(closestPlayer))
					elseif action == 'drag' then
						TriggerServerEvent('esx_policejob:drag', GetPlayerServerId(closestPlayer))
					elseif action == 'put_in_vehicle' then
						TriggerServerEvent('esx_policejob:putInVehicle', GetPlayerServerId(closestPlayer))
					elseif action == 'out_the_vehicle' then
						TriggerServerEvent('esx_policejob:OutVehicle', GetPlayerServerId(closestPlayer))
					elseif action == 'fine' then
						OpenFineMenu(closestPlayer)
					elseif action == 'license' then
						ShowPlayerLicense(closestPlayer)
					elseif action == 'unpaid_bills' then
						OpenUnpaidBillsMenu(closestPlayer)
	 				end

				else
					ESX.ShowNotification(_U('no_players_nearby'))
				end
			end, function(data2, menu2)
				menu2.close()
			end)
```

What do you think ?

**Comment by Khaled-BH** [comment]
do u fix it?


> I modified to :
> 
> ```
> function OpenPoliceActionsMenu()
> 	ESX.UI.Menu.CloseAll()
> 
> 	ESX.UI.Menu.Open(
> 	'default', GetCurrentResourceName(), 'police_actions',
> 	{
> 	        title      = 'Police',
> 		align    = 'bottom-right',
> 		elements = {
> 			{label = _U('citizen_interaction'),	value = 'citizen_interaction'},
> 			{label = _U('vehicle_interaction'),	value = 'vehicle_interaction'},
> 			{label = _U('object_spawner'),		value = 'object_spawner'},
> 			{label = "Envoyer en prison",           value = 'jail_menu'},
> 			{label = "Récupérer de l\'ADN",             	value = 'dna'}
> 		}
> 	}, function(data, menu)
> 
> 		if data.current.value == 'jail_menu' then
>                      TriggerEvent("esx-qalle-jail:openJailMenu")
>                 end
> 
>                 if data.current.value == 'dna' then
> 				local player, distance = ESX.Game.GetClosestPlayer()
>   
>   				if distance ~= -1 and distance <= 3.0 then
>     				TriggerEvent('jsfour-dna:get', player)
>   				end
>   		end
> 
> 		if data.current.value == 'citizen_interaction' then
> 			local elements = {
> 				{label = _U('id_card'),			value = 'identity_card'},
> 				{label = _U('search'),			value = 'body_search'},
> 				{label = _U('handcuff'),		value = 'handcuff'},
> 				{label = _U('drag'),			value = 'drag'},
> 				{label = _U('put_in_vehicle'),	value = 'put_in_vehicle'},
> 				{label = _U('out_the_vehicle'),	value = 'out_the_vehicle'},
> 				{label = _U('fine'),			value = 'fine'},
> 				{label = _U('unpaid_bills'),	value = 'unpaid_bills'}
> 			}
> 
> 			if Config.EnableLicenses then
> 				table.insert(elements, { label = _U('license_check'), value = 'license' })
> 			end
> 		
> 			ESX.UI.Menu.Open(
> 			'default', GetCurrentResourceName(), 'citizen_interaction',
> 			{
> 				title    = _U('citizen_interaction'),
> 				align    = 'bottom-right',
> 				elements = elements
> 			}, function(data2, menu2)
> 				local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
> 				if closestPlayer ~= -1 and closestDistance <= 3.0 then
> 					local action = data2.current.value
> 
> 					if action == 'identity_card' then
> 						OpenIdentityCardMenu(closestPlayer)
> 					elseif action == 'body_search' then
> 						TriggerServerEvent('esx_policejob:message', GetPlayerServerId(closestPlayer), _U('being_searched'))
> 						OpenBodySearchMenu(closestPlayer)
> 					elseif action == 'handcuff' then
> 						TriggerServerEvent('esx_policejob:handcuff', GetPlayerServerId(closestPlayer))
> 					elseif action == 'drag' then
> 						TriggerServerEvent('esx_policejob:drag', GetPlayerServerId(closestPlayer))
> 					elseif action == 'put_in_vehicle' then
> 						TriggerServerEvent('esx_policejob:putInVehicle', GetPlayerServerId(closestPlayer))
> 					elseif action == 'out_the_vehicle' then
> 						TriggerServerEvent('esx_policejob:OutVehicle', GetPlayerServerId(closestPlayer))
> 					elseif action == 'fine' then
> 						OpenFineMenu(closestPlayer)
> 					elseif action == 'license' then
> 						ShowPlayerLicense(closestPlayer)
> 					elseif action == 'unpaid_bills' then
> 						OpenUnpaidBillsMenu(closestPlayer)
> 	 				end
> 
> 				else
> 					ESX.ShowNotification(_U('no_players_nearby'))
> 				end
> 			end, function(data2, menu2)
> 				menu2.close()
> 			end)
> ```
> 
> What do you think ?

**Comment by Antykors** [comment]
Yes it's fix. Sorry for no response

**Comment by Kaijunoki** [comment]
```
ESX.UI.Menu.Open(
			'default', GetCurrentResourceName(), 'citizen_interaction',
			{
				title    = _U('citizen_interaction'),
				align    = 'top-left',
				elements = elements
			}, function(data2, menu2)
				local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
				if closestPlayer ~= -1 and closestDistance <= 3.0 then
					local action = data2.current.value
					local player, distance = ESX.Game.GetClosestPlayer()

					if action == 'identity_card' then
						OpenIdentityCardMenu(closestPlayer)
					elseif action == 'body_search' then
						TriggerServerEvent('esx_policejob:message', GetPlayerServerId(closestPlayer), _U('being_searched'))
						OpenBodySearchMenu(closestPlayer)
					elseif action == 'handcuff' then
						TriggerServerEvent('esx_policejob:handcuff', GetPlayerServerId(closestPlayer))
					elseif action == 'drag' then
						TriggerServerEvent('esx_policejob:drag', GetPlayerServerId(closestPlayer))
					elseif action == 'put_in_vehicle' then
						TriggerServerEvent('esx_policejob:putInVehicle', GetPlayerServerId(closestPlayer))
					elseif action == 'out_the_vehicle' then
						TriggerServerEvent('esx_policejob:OutVehicle', GetPlayerServerId(closestPlayer))
					elseif action == 'fine' then
						OpenFineMenu(closestPlayer)
					elseif action == 'license' then
						ShowPlayerLicense(closestPlayer)
					elseif action == 'unpaid_bills' then
						OpenUnpaidBillsMenu(closestPlayer)
					elseif action == 'dna' then
						TriggerEvent('jsfour-dna:get', player)
					end
```
try this, for myserver it's work

**Comment by Khaled-BH** [comment]
can i have the full file :(

**Comment by Khaled-BH** [comment]
> ```
> ESX.UI.Menu.Open(
> 			'default', GetCurrentResourceName(), 'citizen_interaction',
> 			{
> 				title    = _U('citizen_interaction'),
> 				align    = 'top-left',
> 				elements = elements
> 			}, function(data2, menu2)
> 				local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
> 				if closestPlayer ~= -1 and closestDistance <= 3.0 then
> 					local action = data2.current.value
> 					local player, distance = ESX.Game.GetClosestPlayer()
> 
> 					if action == 'identity_card' then
> 						OpenIdentityCardMenu(closestPlayer)
> 					elseif action == 'body_search' then
> 						TriggerServerEvent('esx_policejob:message', GetPlayerServerId(closestPlayer), _U('being_searched'))
> 						OpenBodySearchMenu(closestPlayer)
> 					elseif action == 'handcuff' then
> 						TriggerServerEvent('esx_policejob:handcuff', GetPlayerServerId(closestPlayer))
> 					elseif action == 'drag' then
> 						TriggerServerEvent('esx_policejob:drag', GetPlayerServerId(closestPlayer))
> 					elseif action == 'put_in_vehicle' then
> 						TriggerServerEvent('esx_policejob:putInVehicle', GetPlayerServerId(closestPlayer))
> 					elseif action == 'out_the_vehicle' then
> 						TriggerServerEvent('esx_policejob:OutVehicle', GetPlayerServerId(closestPlayer))
> 					elseif action == 'fine' then
> 						OpenFineMenu(closestPlayer)
> 					elseif action == 'license' then
> 						ShowPlayerLicense(closestPlayer)
> 					elseif action == 'unpaid_bills' then
> 						OpenUnpaidBillsMenu(closestPlayer)
> 					elseif action == 'dna' then
> 						TriggerEvent('jsfour-dna:get', player)
> 					end
> ```
> 
> try this, for myserver it's work

**Comment by Kaijunoki** [comment]
> can i have the full file :(

could you please show me your code? in esx_policejob>client>main.lua
Maybe I can help you

**Comment by Khaled-BH** [comment]
Done i make it.

**Comment by Kaijunoki** [comment]
> Done i make it.

Is it work?

**Comment by Khaled-BH** [comment]
yeah

> > Done i make it.
> 
> Is it work?

**Comment by WhiteWolfWCY** [comment]
I need to make it work, can you send the whole main.lua file? It doesn't show an option DNA in F6 :/
