### ISSUE TITLE
Marker doesn't appear.

### ISSUE THREAD

**Issue by DiabolicMzz** [jonassvensson4/jsfour-dna#6]
So yesterday i did run some tests and find out that if i stop jsfour-dna then start and change job to any police grade it works, but when the server starts it just stays dead. Besides this, the script is working well.

**Comment by jnsvns** [comment]
It doesn't make sense that you need to restart it and then set your job. If that works it should also work if you set your job on the first start. 

If that's the case you might wanna have a look at your start order and also log what job ESX returns.

**Comment by DiabolicMzz** [comment]
It's working now lol made a typo, my bad. Thanks for this great release.
